export const ACTIVATION_REQUEST = 'ACTIVATION_REQUEST';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';
export const SET_ACTIVATION_DATA = 'SET_ACTIVATION_DATA';
export const SET_ACTIVATION_ERROR_MESSAGE = 'SET_ACTIVATION_ERROR_MESSAGE';
export const SET_ACTIVATION_SUCCESS_MESSAGE = 'SET_ACTIVATION_SUCCESS_MESSAGE';
