export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const ON_CHANGE_REGISTRATION_FIELD = 'ON_CHANGE_REGISTRATION_FIELD';
export const ON_FOCUS_REGISTRATION_FIELD = 'ON_FOCUS_REGISTRATION_FIELD';

export const SET_REGISTRATION_ERROR_MESSAGE = 'SET_REGISTRATION_ERROR_MESSAGE';
export const SET_REGISTRATION_SUCCESS_MESSAGE = 'SET_REGISTRATION_SUCCESS_MESSAGE';

export const TOGGLE_REGISTRATION_PASSWORD_VISIBILITY = 'TOGGLE_REGISTRATION_PASSWORD_VISIBILITY';
export const TOGGLE_REGISTRATION_REPEAT_PASSWORD_VISIBILITY = 'TOGGLE_REGISTRATION_REPEAT_PASSWORD_VISIBILITY';
