language: node_js
branches:
  only:
  - master
  - development
node_js:
- stable
after_success: npm run coverage && ./tools/merge-development-with-master.sh
sudo: false
deploy:
  provider: heroku
  app: phpiotr
  on: master
  run:
  - nf start
  api_key:
    secure: 1Fwwlx0if9IbHyRLWgodCTWEAKiylm+rT469wdDcP2g3r00s5HHpPmMuiLwKmgDfZqaIbi4lO/yPd8bkjWdjgqgypHK7u1laotlPdZmIJ8VmT6eZEFRG23QkNm7XzmP6AT283CzfXXF6XiRcGL3zfYZo+YcjuEb/WEhQWJ33GPTXRJHpOmFjiSNDbD7P0khjGzKMKAEFyeOw0EqF3LOBuwyNIruZ09ukI43WIAZYr1SzksQcv+EhkS2jPcopnLO9moUxB+hs+3yptFOakCWOginJJnjqx6gYycODNshtpWLOxHg/c+yGmYLuKlO+bZq5uq5L832FMR2tQhuEHhkyCQG+q3HfXXVed/4ztVCXObMYd8n80vuMEuPDXO2OWtNO/CN3KqbUzcdm0gXmEkp9wOLsPHLYMODbQx6WxoGcoMrJqyUTNA/cJrRm4yGAm975oeoe5CaC5T5WDm2yvrD3LsQEpFAhKldXyp1f5xqrgNvhJ77YMqFbO4F79zfgJt0YsX5fbasEoBwBxvuFbUl4vQZdHYsfjvRwEbbeedtsmWtE6egcNBULH3kjqly5G0+jDk5/dgRtJxzzAu4M+8TAQ36kr3tlod/eWn3kwMm5F5sDckJZKzqs+2wy4r41y/gBSfj26y2QlDaOJwqzK8lc/AIy8glAybQlrk1x+dNRRAY=
