export const TOGGLE_IS_DRAWER_OPEN = 'TOGGLE_IS_DRAWER_OPEN';
export const TOGGLE_IS_BOOKING_DELETE_DIALOG_OPEN = 'TOGGLE_IS_BOOKING_DELETE_DIALOG_OPEN';
export const SET_APP_BAR_TITLE = 'SET_APP_BAR_TITLE';
export const SET_CURRENT_BOOKING = 'SET_CURRENT_BOOKING';
