export const SET_RECOVERY_EMAIL = 'SET_RECOVERY_EMAIL';
export const SET_IS_RECOVERED = 'SET_IS_RECOVERED';
export const SET_RECOVERY_ERROR_MESSAGE = 'SET_RECOVERY_ERROR_MESSAGE';
export const ACCOUNT_RECOVERY_REQUEST = 'ACCOUNT_RECOVERY_REQUEST';
export const ACCOUNT_RECOVERY_SUCCESS = 'ACCOUNT_RECOVERY_SUCCESS';
export const ACCOUNT_RECOVERY_FAILURE = 'ACCOUNT_RECOVERY_FAILURE';