export const HOSTELS_REQUEST = 'HOSTELS_REQUEST';
export const HOSTELS_SUCCESS = 'HOSTELS_SUCCESS';
export const HOSTELS_FAILURE = 'HOSTELS_FAILURE';
export const ADD_HOSTEL_REQUEST = 'ADD_HOSTEL_REQUEST';
export const ADD_HOSTEL_SUCCESS = 'ADD_HOSTEL_SUCCESS';
export const ADD_HOSTEL_FAILURE = 'ADD_HOSTEL_FAILURE';