export const TRAINS_REQUEST = 'TRAINS_REQUEST';
export const TRAINS_SUCCESS = 'TRAINS_SUCCESS';
export const TRAINS_FAILURE = 'TRAINS_FAILURE';
export const ADD_TRAIN_REQUEST = 'ADD_TRAIN_REQUEST';
export const ADD_TRAIN_SUCCESS = 'ADD_TRAIN_SUCCESS';
export const ADD_TRAIN_FAILURE = 'ADD_TRAIN_FAILURE';