export const PLANES_REQUEST = 'PLANES_REQUEST';
export const PLANES_SUCCESS = 'PLANES_SUCCESS';
export const PLANES_FAILURE = 'PLANES_FAILURE';
export const ADD_PLANE_REQUEST = 'ADD_PLANE_REQUEST';
export const ADD_PLANE_SUCCESS = 'ADD_PLANE_SUCCESS';
export const ADD_PLANE_FAILURE = 'ADD_PLANE_FAILURE';