export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const ON_CHANGE_LOGIN_FIELD = 'ON_CHANGE_LOGIN_FIELD';
export const ON_FOCUS_LOGIN_FIELD = 'ON_FOCUS_LOGIN_FIELD';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const SET_LOGIN_ERROR_MESSAGE = 'SET_LOGIN_ERROR_MESSAGE';
export const SET_LOGIN_SUCCESS_MESSAGE = 'SET_LOGIN_SUCCESS_MESSAGE';
export const TOGGLE_LOGIN_PASSWORD_VISIBILITY = 'TOGGLE_LOGIN_PASSWORD_VISIBILITY';
