export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const ACTIVATION_REQUEST = 'ACTIVATION_REQUEST';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';

export const ON_CHANGE_LOGIN_FIELD = 'ON_CHANGE_LOGIN_FIELD';
export const ON_FOCUS_LOGIN_FIELD = 'ON_FOCUS_LOGIN_FIELD';
export const ON_CHANGE_REGISTRATION_FIELD = 'ON_CHANGE_REGISTRATION_FIELD';
export const ON_FOCUS_REGISTRATION_FIELD = 'ON_FOCUS_REGISTRATION_FIELD';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_ACTIVATION_DATA = 'SET_ACTIVATION_DATA';

//Account recovery
export const SET_RECOVERY_EMAIL = 'SET_RECOVERY_EMAIL';
export const SET_IS_RECOVERED = 'SET_IS_RECOVERED';
export const SET_RECOVERY_ERROR_MESSAGE = 'SET_RECOVERY_ERROR_MESSAGE';
export const ACCOUNT_RECOVERY_REQUEST = 'ACCOUNT_RECOVERY_REQUEST';
export const ACCOUNT_RECOVERY_SUCCESS = 'ACCOUNT_RECOVERY_SUCCESS';
export const ACCOUNT_RECOVERY_FAILURE = 'ACCOUNT_RECOVERY_FAILURE';

// Reset password
export const SET_RESET_PASSWORD_INPUT_VALUE = 'SET_RESET_PASSWORD_INPUT_VALUE';
export const SET_RESET_PASSWORD_ERROR_MESSAGE = 'SET_RESET_PASSWORD_ERROR_MESSAGE';
export const SET_IS_RESET_PASSWORD = 'SET_IS_RESET_PASSWORD';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

