export const REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const REPORT_FAILURE = 'GET_REPORT_FAILURE';
export const TOGGLE_DETAILS_OPEN = 'TOGGLE_DETAILS_OPEN';